// Copyright (c) 2023 Dashlane Inc
// This software is licensed under the MIT License. See the LICENSE.md file for details.

import Foundation
import CryptoKit

/// Open Box to initialise the vault exchange.
///
/// The OpenBox is generated by the vault receiver and transmitted to the Vault provider.
public struct OpenBox: Codable, Equatable {
    /// Public Key of the Vault receiver used to share the vault content symmetric key with the vault source.
    public let publicKey: PublicKey

    /// Open Box to initialise the vault exchange.
    /// - Parameter publicKey: Public Key of the Vault receiver used to share the vault content symmetric key with the vault provider.
    public init(publicKey: PublicKey) {
        self.publicKey = publicKey
    }
}
